import { test, expect, open, go, setPersona, setUpTo, resetDemo, mainText, expectNoHorizontalScroll, assertRoute } from './helpers'
import ExcelJS from 'exceljs'
import path from 'node:path'
import { createSeed, itemByTag, TIVERNE_ID, MERROWGATE_ID, DURNLEY_ID } from '../src/domain/seed/world'
import { lotPrivateStrings, projectPrivateStrings, INTERNAL_ID } from '../src/domain/privacy/privateStrings'
import { dateFormats } from '../src/domain/dates'
import { LABELS } from '../src/domain/reference/labels'

const P = { tom: 'per_tom', dana: 'per_dana', priya: 'per_priya', isla: 'per_isla', marcus: 'per_marcus', operator: 'per_operator' }
const seed = createSeed()
const th01 = itemByTag(seed, 'TH-01')

function allLotPrivateStrings(): string[] {
  const out = new Set<string>()
  for (const lot of Object.values(seed.lots)) {
    const item = seed.items[lot.itemId]
    for (const s of lotPrivateStrings(lot, item, seed.buildings[item.buildingId], seed)) out.add(s)
  }
  out.add('TH-12')
  for (const s of dateFormats('2027-01-25')) out.add(s)
  return [...out]
}
const LOT_PRIVATE = allLotPrivateStrings()
/** Exchanged after confirmation (04 section 3, rule 3) for the two parties to the deal, plus the tested date derived from the handover (rule 15). */
const EXCHANGED = ['Ostlea Estates', 'Tom Ashby', ...dateFormats('2027-03-15'), ...dateFormats('2027-03-29')]
const PROJECT_PRIVATE = projectPrivateStrings(seed.projects[MERROWGATE_ID], seed)

async function expectNoLotPrivate(page: import('@playwright/test').Page, allowExchanged = false) {
  const text = await mainText(page)
  for (const s of LOT_PRIVATE) {
    if (allowExchanged && EXCHANGED.includes(s)) continue
    expect(text, `buyer-side content leaks "${s}"`).not.toContain(s)
  }
  expect(text).not.toMatch(INTERNAL_ID)
}

const label = (page: import('@playwright/test').Page, id: keyof typeof LABELS) => expect(page.getByTestId(`label-${id}`).first()).toContainText(LABELS[id])

test.describe.configure({ mode: 'serial' })

test('steps 1 to 12 on fresh seed', async ({ page, entry }, testInfo) => {
  test.setTimeout(240_000)
  await open(page, entry)
  await resetDemo(page)
  await label(page, 'L1')

  // Step 1. Capture on site (Dana, 390 px)
  await page.setViewportSize({ width: 390, height: 844 })
  await setPersona(page, P.dana)
  await go(page, `/buildings/${TIVERNE_ID}/capture`)
  assertRoute(page)
  await label(page, 'L8')
  await page.getByTestId('capture-text').fill('30 no. 203x203x46 UC, 3.2m long, bolted, roof plant room')
  await page.getByTestId('capture-assist').click()
  await label(page, 'L2')
  await expect(page.getByTestId('capture-family')).toHaveValue('steel_section')
  await expect(page.getByTestId('capture-section')).toHaveValue('UC 203x203x46')
  await expect(page.getByTestId('capture-pieces')).toHaveValue('30')
  await expect(page.getByTestId('capture-length')).toHaveValue('3.2')
  await expect(page.getByTestId('capture-recoverability-A')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('capture-location')).toHaveValue('roof plant room')
  await page.getByTestId('capture-photo').setInputFiles(path.resolve('e2e/fixtures/sample-photo.jpg'))
  await expect(page.getByTestId('capture-photos')).toBeVisible()
  await page.getByTestId('capture-condition-A').click()
  await expectNoHorizontalScroll(page)
  const small = await page.evaluate(() => {
    const out: string[] = []
    for (const el of document.querySelectorAll('main button, main input, main select, main textarea')) {
      const r = (el as HTMLElement).getBoundingClientRect()
      if (r.height > 0 && r.height < 44) out.push(`${el.tagName} ${(el as HTMLElement).id || (el as HTMLElement).dataset.testid || ''} ${r.height}`)
    }
    return out
  })
  expect(small, 'touch targets under 44 px').toEqual([])
  await page.getByTestId('capture-save').click()
  await expect(page.getByTestId('saved-tag')).toHaveText('TH-12')
  await expect(page.getByTestId('saved-mass')).toHaveText('4.43 t')
  await expect(page.getByTestId('saved-carbon')).toHaveText('7.5 tCO2e')
  await expect(page.getByTestId('saved-guide')).toHaveText('£670 per tonne')
  await expect(page.getByTestId('saved-photos')).toHaveText('1 photo, Private')

  // Step 2. Decide what to recover (Tom)
  await page.setViewportSize({ width: 1440, height: 900 })
  await setPersona(page, P.tom)
  await go(page, `/buildings/${TIVERNE_ID}/priority`)
  assertRoute(page)
  await expect(page.locator('[data-testid^="priority-row-"]')).toHaveCount(12)
  await expect(page.getByTestId('priority-tag-text-1')).toHaveText('TH-02')
  await expect(page.getByTestId('priority-score-1')).toHaveText('68.7')
  await expect(page.getByTestId('priority-tag-text-12')).toHaveText('TH-12')
  await expect(page.getByTestId('priority-score-12')).toHaveText('14.5')
  await expect(page.getByTestId('priority-reason-TH-09')).toContainText('Recycle rather than recover')
  await expect(page.getByTestId('priority-reason-TH-10')).toContainText('Recycle rather than recover')
  await expect(page.getByTestId('priority-recoverable')).toHaveText('£202,966.91')
  await expect(page.getByTestId('priority-top-three')).toHaveText('54.2%')
  await label(page, 'L2')
  await page.getByTestId('priority-calc-1').click()
  const calc = page.getByTestId('priority-calc-1-panel')
  await expect(calc).toContainText('22.7')
  await expect(calc).toContainText('30.0')
  await expect(calc).toContainText('10.0')
  await expect(calc).toContainText('6.0')
  await page.keyboard.press('Escape')

  // Step 3. Publish without leaking (Tom)
  await go(page, `/buildings/${TIVERNE_ID}/listings`)
  assertRoute(page)
  await expect(page.locator('[data-testid^="lot-visibility-"]').filter({ hasText: 'Shared privately with selected projects' })).toHaveCount(5)
  await page.getByTestId('select-lot-TH-01').click()
  await page.getByTestId('publish-visibility').selectOption('open')
  await expect(page.getByTestId('disclosure-score')).toHaveText('10')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Low')
  await label(page, 'L9')
  await page.getByTestId('location-level').selectOption('local_authority')
  await expect(page.getByTestId('disclosure-score')).toHaveText('25')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Medium')
  await expect(page.getByTestId('disclosure-inferences')).toContainText('Local authority shown')
  await label(page, 'L34')
  await page.getByTestId('timing-level').selectOption('month')
  await expect(page.getByTestId('disclosure-score')).toHaveText('35')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Medium')
  await page.getByTestId(`photo-public-${th01.id}-pho_th01-tick`).check()
  await expect(page.getByTestId('disclosure-score')).toHaveText('45')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('High')
  await expect(page.getByTestId('publish')).toBeDisabled()
  await expect(page.getByTestId('publish-blocked')).toHaveText('Publishing is blocked at this disclosure level.')
  await page.getByTestId('reset-defaults').click()
  await expect(page.getByTestId('disclosure-score')).toHaveText('10')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Low')
  await expect(page.getByTestId('preview-location')).toHaveText('Central London')
  await expect(page.getByTestId('preview-availability')).toHaveText('Available from Q1 2027')
  await expect(page.getByTestId('publish-ask')).toHaveValue('800')
  await expect(page.getByTestId('publish-reserve')).toHaveValue('730')
  await page.getByTestId('publish').click()
  await expect(page.getByTestId('lot-visibility-TH-01')).toHaveText('Published to the marketplace')
  await expect(page.getByTestId('lot-public-id-TH-01')).toHaveText('L-9F4CQQ')
  await expect(page.getByTestId('selected-ask')).toContainText('£800 per tonne')
  await expect(page.getByTestId('selected-reserve')).toContainText('£730 per tonne')
  await expect(page.getByTestId('holding-line').first()).toHaveText('Holding unsold stock would use up the gain over scrap in about 75.9 months')
  await label(page, 'L28')

  // Step 4. Find it (Priya)
  await setPersona(page, P.priya)
  await go(page, '/market')
  assertRoute(page)
  await expect(page.getByTestId('browse-card-L-9F4CQQ')).toBeVisible()
  await expectNoLotPrivate(page)
  await page.getByTestId('browse-card-L-9F4CQQ').locator('a').click()
  await expect(page).toHaveURL(/#\/market\/L-9F4CQQ$/)
  assertRoute(page)
  await expect(page.locator('main svg[role="img"]').first()).toBeVisible()
  await expect(page.getByTestId('listing-title')).toHaveText('UB 457x191x67, 7.5 m')
  await expect(page.getByTestId('listing-quantity')).toHaveText('48 pieces')
  await expect(page.getByTestId('listing-mass')).toHaveText('24.16 t')
  await expect(page.getByTestId('listing-grade')).toHaveText('To be confirmed by testing')
  await expect(page.getByTestId('listing-test-status')).toHaveText('Untested')
  await expect(page.getByTestId('listing-location')).toHaveText('Central London')
  await expect(page.getByTestId('listing-availability')).toHaveText('Available from Q1 2027')
  await expect(page.getByTestId('listing-price')).toHaveText('£715 to £825 per tonne')
  await expect(page.getByTestId('listing-signal')).toHaveText('Market signal: High demand')
  await expect(page.getByTestId('listing-carbon')).toHaveText('41.0 tCO2e')
  await expect(page.getByTestId('listing-listed')).toHaveText('Surveyed. Listed October 2026.')
  await label(page, 'L10')
  await expectNoLotPrivate(page)
  for (const s of lotPrivateStrings(seed.lots['lot_7fk2qa'], th01, seed.buildings[TIVERNE_ID], seed)) expect(page.url()).not.toContain(encodeURIComponent(s))
  await page.getByTestId('listing-carbon-calc').click()
  await expect(page.getByTestId('listing-carbon-calc-panel')).toContainText(LABELS.L11)
  await expect(page.getByTestId('listing-carbon-calc-panel')).toContainText(LABELS.L12)
  await page.keyboard.press('Escape')
  await page.getByTestId('listing-price-calc').click()
  await expect(page.getByTestId('listing-price-calc-panel')).toContainText(LABELS.L2)
  await page.keyboard.press('Escape')

  // Step 5. Match a schedule (Isla, the client)
  await setPersona(page, P.isla)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  assertRoute(page)
  await page.getByTestId('load-sample-schedule').click()
  await expect(page.getByTestId('match-lines')).toHaveText('6 lines, 102 members')
  await expect(page.getByTestId('match-matched')).toHaveText('60 of 102 members matched (58.8%)')
  await label(page, 'L6')
  await page.getByTestId('open-terms').click()
  await label(page, 'L7')
  await page.getByTestId('accept-terms').click()
  await expect(page.getByTestId('match-matched')).toHaveText('96 of 102 members matched (94.1%)')
  await expect(page.getByTestId('match-open-only')).toHaveText('Open market only: 60 of 102')
  const alloc = async (ref: string, id: string, pieces: string) => expect(page.getByTestId(`alloc-pieces-${ref}-${id}`)).toHaveText(pieces)
  await alloc('R1', 'L-9F4CQQ', '48')
  await alloc('R1', 'L-NHZ32R', '4')
  await alloc('R2', 'L-WPX5A6', '12')
  await alloc('R3', 'L-MNY55K', '10')
  await alloc('R4', 'L-6DN4K3', '8')
  await expect(page.getByTestId('reason-R5')).toHaveText('No stock long enough (longest visible in this serial size is 9.5 m)')
  await alloc('R6', 'L-FQK92P', '14')
  await expect(page.getByTestId('alloc-storage-R1-L-9F4CQQ')).toHaveText('Storage 13 to 16 months')
  await expect(page.getByTestId('alloc-grade-R1-L-9F4CQQ')).toHaveText('Grade to be confirmed by testing')
  await label(page, 'L2')
  await label(page, 'L4')
  await expectNoLotPrivate(page)
  await page.getByTestId('add-to-plan-R1-L-9F4CQQ').click()
  await expect(page.getByText('The reuse plan has 1 item.')).toBeVisible()

  // Step 6. Bridge the gap (Isla)
  await go(page, `/projects/${MERROWGATE_ID}/plan`)
  assertRoute(page)
  await expect(page.getByTestId('package-route')).toHaveText('Via storage hub')
  await expect(page.getByTestId('package-facility')).toHaveText('Open yard, Tilbury')
  await expect(page.getByTestId('facility-HUB-TILB')).toContainText('Lowest estimated total')
  await expect(page.getByTestId('package-testing')).toBeChecked()
  await expect(page.getByTestId('package-storage')).toHaveText('Storage 13 to 16 months')
  await label(page, 'L5')
  await expect(page.getByTestId('package-line-material')).toHaveText('£18,600.12')
  await expect(page.getByTestId('package-line-testing')).toHaveText('£1,800.00')
  await expect(page.getByTestId('package-line-storage')).toHaveText('£1,352.74')
  await expect(page.getByTestId('package-line-handlingOut')).toHaveText('£217.40')
  await expect(page.getByTestId('package-line-delivery')).toHaveText('£235.80')
  await expect(page.getByTestId('package-total')).toHaveText('£22,206.06')
  await expect(page.getByTestId('package-new')).toHaveText('£23,189.76')
  await expect(page.getByTestId('package-saving')).toHaveText('Saving £983.70 (4.2%)')
  await expect(page.getByTestId('package-break-even')).toHaveText('Break-even storage 27.6 months')
  await expect(page.getByTestId('package-carbon')).toHaveText('Avoided carbon 39.3 tCO2e')
  await expect(page.getByTestId('facility-total-HUB-TILB')).toHaveText('£22,206.06')
  await expect(page.getByTestId('facility-total-HUB-BARK')).toHaveText('£22,779.36')
  await expect(page.getByTestId('facility-total-HUB-PARK')).toHaveText('£26,324.13')
  await expectNoLotPrivate(page)

  // Step 7. Negotiate through an agent (Isla)
  await expect(page.getByTestId('mandate-open')).toHaveValue('700')
  await expect(page.getByTestId('mandate-max')).toHaveValue('780')
  await page.getByTestId('start-negotiation').click()
  await label(page, 'L3')
  const entries = page.locator('[data-testid^="negotiation-entry-"]')
  await expect(entries).toHaveCount(7)
  const texts = await entries.allTextContents()
  expect(texts.map((t) => t.replace(/^(Seller agent|Buyer agent|Outcome)/, '').trim())).toEqual(['Ask £800', 'Bid £700', 'Ask £760', 'Bid £725', 'Ask £745', 'Bid £735', 'Agreed in principle at £740 per tonne'])
  await expect(page.getByTestId('buyer-approve')).toHaveText(LABELS.L21)
  await page.getByTestId('buyer-approve').click()
  await expect(page.getByTestId('package-total')).toHaveText('£21,481.38')
  await expect(page.getByTestId('package-saving')).toHaveText('Saving £1,708.38 (7.4%)')
  await expect(page.getByTestId('plan-status-text-L-9F4CQQ')).toHaveText('Awaiting seller approval')
  expect(await mainText(page)).not.toContain('730')
  await expectNoLotPrivate(page)

  // Step 8. Seller approves (Tom, then Isla)
  await setPersona(page, P.tom)
  await go(page, '/offers')
  assertRoute(page)
  await expect(page.getByTestId('offer-buyer')).toHaveText('Design team, commercial project, Inner London East, needed by Q2 2028')
  await expect(page.getByTestId('offer-price')).toHaveText('£740 per tonne for 48 pieces (24.16 t)')
  await expect(page.getByTestId('offer-hub')).toHaveText('Deliver to: Open yard, Tilbury')
  await expect(page.getByTestId('offer-net')).toHaveText('Net proceeds £15,979.60')
  await expect(page.getByTestId('offer-gain')).toHaveText('Gain over scrap £8,491.24')
  {
    const text = await mainText(page)
    for (const s of PROJECT_PRIVATE) expect(text, `seller-side content leaks "${s}"`).not.toContain(s)
  }
  await page.getByTestId('seller-approve').click()
  await label(page, 'L22')
  await expect(page.getByTestId('seller-deal-status')).toHaveText('Confirmed')
  await expect(page.getByTestId('seller-deal-buyer')).toHaveText('Lantern Quay Developments')
  await expect(page.getByTestId('seller-deal-contact')).toHaveText('Isla Brennan, Lantern Quay Developments')
  await expect(page.getByTestId('seller-deal-handover')).toHaveText('Handover 15 March 2027 at Open yard, Tilbury')
  await expect(page.getByTestId('seller-deal-inbound')).toHaveText('Inbound haulage £248.40, booked')
  {
    const text = await mainText(page)
    for (const s of dateFormats('2028-04-03')) expect(text).not.toContain(s)
    expect(text).not.toMatch(/\b13 months\b/)
    expect(text).not.toContain('21,227.74')
  }
  await setPersona(page, P.isla)
  await go(page, `/projects/${MERROWGATE_ID}/deals`)
  assertRoute(page)
  await expect(page.getByTestId('buyer-deal-status')).toHaveText('Confirmed')
  await expect(page.getByTestId('buyer-deal-seller')).toHaveText('Ostlea Estates')
  await expect(page.getByTestId('buyer-deal-contact')).toHaveText('Tom Ashby')
  await expect(page.getByTestId('buyer-deal-handover')).toHaveText('Handover 15 March 2027')
  await expect(page.getByTestId('buyer-deal-storage')).toHaveText('Storage 13 months')
  await expect(page.getByTestId('buyer-deal-total')).toHaveText('Total £21,227.74')
  await expect(page.getByTestId('buyer-deal-saving')).toHaveText('Saving £1,962.02 (8.5%)')
  await expect(page.getByTestId('buyer-deal-break-even')).toHaveText('Break-even storage 36.2 months')
  await label(page, 'L23')
  await label(page, 'L22')
  await expectNoLotPrivate(page, true)
  await go(page, '/market/L-9F4CQQ')
  await expect(page.getByTestId('listing-title')).toBeVisible()
  await expect(page.locator('main')).toContainText('No longer available')
  await go(page, '/market')
  await expect(page.getByTestId('browse-card-L-9F4CQQ')).toHaveCount(0)

  // Step 9. Logistics (Isla)
  await go(page, `/projects/${MERROWGATE_ID}/deals`)
  await page.getByTestId('arrange-delivery').click()
  await label(page, 'L3')
  await expect(page.getByTestId('quote-Haulier-A')).toContainText("Haulier A£235.803 days' notice")
  await expect(page.getByTestId('quote-Haulier-C')).toContainText("Haulier C£260.105 days' notice")
  await expect(page.getByTestId('quote-Haulier-B')).toContainText("Haulier B£264.252 days' notice")
  await expect(page.getByTestId('quote-Haulier-A')).toContainText('Cheapest that meets the dates')
  await page.getByTestId('approve-booking').click()
  await expect(page.getByTestId('delivery-booked')).toContainText('Delivery booked for 3 April 2028')
  await expect(page.getByTestId('custody-agreed')).toContainText('Agreed 7 October 2026')
  await expect(page.getByTestId('custody-agreed')).toContainText('done')
  await expect(page.getByTestId('custody-handover')).toContainText('Handover at hub 15 March 2027')
  await expect(page.getByTestId('custody-tested')).toContainText('Tested 29 March 2027')
  await expect(page.getByTestId('custody-delivered')).toContainText('Delivered 3 April 2028')
  await expect(page.getByTestId('custody-delivered')).toContainText('planned')
  expect(await mainText(page)).not.toContain('248.40')
  await expectNoLotPrivate(page, true)

  // Step 10. Prove it (Marcus)
  await setPersona(page, P.marcus)
  await go(page, `/projects/${MERROWGATE_ID}/compliance`)
  assertRoute(page)
  await expect(page.getByTestId('content-secured')).toHaveText('Reused and recycled content by value: 20.06% secured')
  await expect(page.getByTestId('content-aim')).toHaveText('Aim: at least 20%')
  await expect(page.getByTestId('content-with-plan')).toHaveText('With plan 20.06%')
  await expect(page.getByTestId('content-without-reuse')).toHaveText('Without reuse 17.62%')
  await expect(page.getByTestId('contribution-bom08')).toHaveText('+2.00')
  await expect(page.getByTestId('contribution-bom10')).toHaveText('+0.29')
  await expect(page.getByTestId('contribution-bom03')).toHaveText('+0.15')
  await expect(page.getByTestId('avoided-carbon')).toHaveText('Upfront carbon avoided against buying new (A1-A4): 87.1 tCO2e')
  await expect(page.getByTestId('reclaimed-mass')).toHaveText('Reclaimed material secured: 126.96 t')
  await label(page, 'L17')
  await label(page, 'L16')
  await label(page, 'L15')
  await label(page, 'L11')
  await label(page, 'L19')
  await expectNoLotPrivate(page, true)
  {
    const text = await mainText(page)
    expect(text).not.toContain('Durnley House')
    expect(text).not.toContain('Pellory Estates')
  }
  const dl1 = page.waitForEvent('download')
  await page.getByTestId('export-compliance').click()
  const d1 = await dl1
  expect(d1.suggestedFilename()).toBe('merrowgate-wharf-compliance-2026-10-07.xlsx')
  const f1 = path.join(testInfo.outputDir, d1.suggestedFilename())
  await d1.saveAs(f1)
  {
    const wb = new ExcelJS.Workbook()
    await wb.xlsx.readFile(f1)
    expect(wb.worksheets.map((w) => w.name)).toContain('Summary')
    const all: string[] = [wb.creator ?? '', wb.title ?? '']
    wb.eachSheet((ws) => {
      all.push(ws.name)
      ws.eachRow((row) => row.eachCell((c) => all.push(String(c.text ?? ''))))
    })
    const text = all.join('\n')
    expect(text).toContain(LABELS.L20)
    for (const s of LOT_PRIVATE) if (!EXCHANGED.includes(s)) expect(text, `workbook leaks "${s}"`).not.toContain(s)
  }
  // Print layout: A4, no clipped table, and a PDF.
  await page.emulateMedia({ media: 'print' })
  await page.setViewportSize({ width: 794, height: 1123 })
  const clipped = await page.evaluate(() => [...document.querySelectorAll('main table')].filter((t) => t.scrollWidth > (t.parentElement?.clientWidth ?? 0) + 1).length)
  expect(clipped, 'tables clipped in print').toBe(0)
  await expect(page.getByTestId('label-L20').first()).toBeVisible()
  const pdf = await page.pdf({ format: 'A4', printBackground: true })
  expect(pdf.byteLength).toBeGreaterThan(1000)
  await page.emulateMedia({ media: 'screen' })
  await page.setViewportSize({ width: 1440, height: 900 })

  // Step 11. Ingest a demolition bill (Marcus)
  await go(page, `/engagements/${DURNLEY_ID}/waste`)
  assertRoute(page)
  await page.getByTestId('load-sample-bill').click()
  await label(page, 'L2')
  await expect(page.getByTestId('rows-read')).toHaveText('20 rows read')
  await expect(page.getByTestId('rows-skipped')).toHaveText('2 title rows and 1 total row skipped')
  await expect(page.getByTestId('confidence-counts')).toHaveText('14 high confidence, 5 medium, 1 needs review')
  await expect(page.getByTestId('stated-total')).toHaveText('Stated total 11,369.2 t matches the rows')
  await expect(page.getByTestId('diversion')).toHaveText('Diversion from landfill 97.5%')
  await expect(page.getByTestId('unresolved-notice')).toHaveText('1 row (6.0 t) is not counted until it is reviewed')
  await page.getByTestId('row-20-stream').selectOption('mixed_cd')
  await page.getByTestId('row-20-destination').selectOption('landfill')
  await expect(page.getByTestId('diversion')).toHaveText('Diversion from landfill 97.4%')
  await expect(page.getByTestId('diversion-aim')).toHaveText('Aim: at least 95%')
  await expect(page.getByTestId('reuse-rate')).toHaveText('Reuse rate 3.1%')
  await expect(page.getByTestId('reused-off-site')).toHaveText('Components reused off site 351.0 t')
  await expect(page.getByTestId('recycled-on-site')).toHaveText('Recycled on site 1,200.0 t')
  await expect(page.getByTestId('carbon-benefit')).toHaveText('Potential carbon benefit of reuse 461.4 tCO2e')
  await expect(page.getByTestId('hazardous')).toHaveText('Hazardous waste 14.2 t, reported separately')
  await expect(page.getByTestId('intensity')).toHaveText('0.72 t per m2 GIA')
  await label(page, 'L18')
  await label(page, 'L13')
  await label(page, 'L16')
  {
    const text = await mainText(page)
    for (const s of PROJECT_PRIVATE) expect(text, `waste screen leaks "${s}"`).not.toContain(s)
  }
  const dl2 = page.waitForEvent('download')
  await page.getByTestId('export-waste').click()
  const d2 = await dl2
  expect(d2.suggestedFilename()).toBe('durnley-house-waste-and-reuse-2026-10-07.xlsx')
  const f2 = path.join(testInfo.outputDir, d2.suggestedFilename())
  await d2.saveAs(f2)
  {
    const wb = new ExcelJS.Workbook()
    await wb.xlsx.readFile(f2)
    expect(wb.worksheets.map((w) => w.name)).toContain('Arisings')
  }

  // Step 12. Run the platform (operator)
  await setPersona(page, P.operator)
  await go(page, '/operator/ledger')
  assertRoute(page)
  const deal = page.getByTestId('ledger-deal-L-9F4CQQ')
  await expect(deal.getByTestId('ledger-line-commission')).toHaveText('Commission £1,430.04')
  await expect(deal.getByTestId('ledger-line-brokerage')).toHaveText('Storage brokerage £153.39')
  await expect(deal.getByTestId('ledger-line-referral')).toHaveText('Testing referral £180.00')
  await expect(deal.getByTestId('ledger-line-transport')).toHaveText('Transport margin £24.21')
  await expect(deal.getByTestId('ledger-deal-total')).toHaveText('Deal total £1,787.64')
  await expect(page.getByTestId('ledger-to-date')).toHaveText('Transactions and data to date £16,192.44')
  await expect(page.getByTestId('ledger-subscriptions')).toHaveText('Subscriptions, annual £70,800.00')
  await label(page, 'L31')
  {
    const text = await mainText(page)
    for (const s of ['Tiverne House', 'Garnet Row', 'Corvane Insurance', 'Meridale Partners']) expect(text).not.toContain(s)
  }
  await go(page, '/operator/models')
  await expect(page.getByTestId('model-agency')).toHaveText('Agency £1,787.64, no capital employed')
  await expect(page.getByTestId('model-principal')).toHaveText('Principal: margin £3,785.28 on capital of £16,868.10 (22.4%)')
  await expect(page.getByTestId('model-candidate')).toHaveText('Candidate to buy')
  await expect(page.getByTestId('model-forward')).toHaveText('Forward sale £1,966.39')
  await label(page, 'L29')
  await label(page, 'L30')
  await label(page, 'L2')
})

test('labels off the demo path, P5b, and the three stubs', async ({ page, entry }) => {
  await open(page, entry)
  await resetDemo(page)
  await setPersona(page, P.priya)
  // P5b and L26: a matched-only lot before the terms are accepted shows Not available.
  await go(page, '/market/L-WPX5A6')
  await expect(page.getByTestId('listing-not-available')).toHaveText(LABELS.L26)
  // L14 on unused surplus. L25 on a non-steel listing is reserve copy, so only the client sees it (brief 09 section 13.10).
  await go(page, '/market/L-YZ2C7H')
  await expect(page.getByTestId('listing-carbon')).toHaveText(LABELS.L14)
  await go(page, '/market/L-Q23X7N')
  await expect(page.getByTestId('listing-title')).toBeVisible()
  await expect(page.getByTestId('label-L25')).toHaveCount(0)
  await setPersona(page, P.isla)
  await go(page, '/market/L-Q23X7N')
  await label(page, 'L25')
  // L27 and L24: after the terms, a shared lot reached from the client's matcher, and a plan item for another seller.
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await page.getByTestId('load-sample-schedule').click()
  await page.getByTestId('open-terms').click()
  await page.getByTestId('accept-terms').click()
  await page.getByTestId('alloc-link-R2-L-WPX5A6').click()
  await expect(page.locator('main')).toContainText(LABELS.L27)
  await expectNoLotPrivate(page)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await page.getByTestId('add-to-plan-R1-L-NHZ32R').click()
  await go(page, `/projects/${MERROWGATE_ID}/plan`)
  await label(page, 'L24')
  // Stubs: L33 in each panel.
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await page.getByTestId('stub-bim').click()
  await expect(page.getByTestId('stub-bim-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')
  await setPersona(page, P.dana)
  await go(page, `/buildings/${TIVERNE_ID}/capture`)
  await page.getByTestId('stub-photo').click()
  await expect(page.getByTestId('stub-photo-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')
  await setPersona(page, P.marcus)
  await go(page, `/engagements/${DURNLEY_ID}/waste`)
  await page.getByTestId('stub-pdf').click()
  await expect(page.getByTestId('stub-pdf-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')
  // L32 on Assumptions, the About screen's fictional line, empty model comparison.
  await go(page, '/assumptions')
  await label(page, 'L32')
  await go(page, '/about')
  await expect(page.getByTestId('about-fictional')).toHaveText('Every company, person, building and address in this prototype is fictional.')
  await setPersona(page, P.operator)
  await go(page, '/operator/models')
  await expect(page.locator('main')).toContainText('Confirm a deal to compare models.')
})

test('layout at 1024 and 1440 after the full demo, and reset removes only this app\'s storage', async ({ page, entry }) => {
  test.setTimeout(240_000)
  await open(page, entry)
  await page.evaluate(() => localStorage.setItem('other-app', 'kept'))
  await setUpTo(page, 12)
  const screens: [string, string][] = [
    [P.tom, `/buildings/${TIVERNE_ID}/inventory`], [P.tom, `/buildings/${TIVERNE_ID}/inventory/itm_7fk2qa`], [P.tom, `/buildings/${TIVERNE_ID}/priority`], [P.tom, `/buildings/${TIVERNE_ID}/listings`], [P.tom, '/offers'],
    [P.priya, '/market'], [P.priya, '/market/L-NHZ32R'], [P.isla, `/projects/${MERROWGATE_ID}/match`], [P.isla, `/projects/${MERROWGATE_ID}/plan`], [P.isla, `/projects/${MERROWGATE_ID}/deals`],
    [P.marcus, `/projects/${MERROWGATE_ID}/compliance`], [P.marcus, `/engagements/${DURNLEY_ID}/waste`], [P.operator, '/operator/ledger'], [P.operator, '/operator/models'], [P.operator, '/assumptions'], [P.operator, '/about'],
  ]
  for (const width of [1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const [persona, route] of screens) {
      await setPersona(page, persona)
      await go(page, route)
      await expect(page.locator('main h1').first()).toBeVisible()
      await expectNoHorizontalScroll(page)
    }
  }
  await go(page, '/')
  await resetDemo(page)
  const keys = await page.evaluate(() => Object.keys(localStorage))
  expect(keys).toContain('other-app')
  expect(keys.filter((k) => k.startsWith('tallyard-v05') && k !== 'tallyard-v05-state')).toEqual([])
  const dbs = await page.evaluate(async () => (await indexedDB.databases()).map((d) => d.name))
  expect(dbs).not.toContain('tallyard-v05-photos')
  await setPersona(page, P.tom)
  await go(page, `/buildings/${TIVERNE_ID}/inventory`)
  await expect(page.getByTestId('inventory-row-TH-12')).toHaveCount(0)
  await expect(page.getByTestId('inventory-row-TH-11')).toBeVisible()
})
