// The end-to-end suite, part 1 (brief/09-V1-PRODUCT.md sections 9 and 13.14): the twelve-step replay on the version
// 1.0 routes and personas, the labels and privacy checks off the path, and the layout and reset checks.
// The role journeys are in journeys.spec.ts. Each test starts from a fresh seed.
import { test, expect, P, seed, LOT_PRIVATE, EXCHANGED, projectPrivate, fresh, open, go, setPersona, setUpTo, resetDemo, mainText, label, expectNoLotPrivate, expectNoProjectPrivate, expectArchitectOnly, expectNoHorizontalScroll, expectTouchTargets, assertRoute, workbookText } from './helpers'
import path from 'node:path'
import { itemByTag, TIVERNE_ID, HARROWDEN_ID, MERROWGATE_ID, SALLOW_ID, FERRYMOOR_ID, DURNLEY_ID } from '../src/domain/seed/world'
import { lotPrivateStrings } from '../src/domain/privacy/privateStrings'
import { dateFormats } from '../src/domain/dates'
import { LABELS } from '../src/domain/reference/labels'

const th01 = itemByTag(seed, 'TH-01')
const PROJECT_PRIVATE = projectPrivate(MERROWGATE_ID)

test.describe.configure({ mode: 'serial' })

test('steps 1 to 12 on fresh seed, on the version 1.0 routes and personas', async ({ page, entry }, testInfo) => {
  test.setTimeout(240_000)
  await fresh(page, entry)
  await label(page, 'L1')

  // Step 1. Capture on site (Dana, 390 px)
  await page.setViewportSize({ width: 390, height: 844 })
  await setPersona(page, P.dana)
  await go(page, `/buildings/${TIVERNE_ID}/capture`)
  assertRoute(page)
  await label(page, 'L8')
  await page.getByTestId('capture-text').fill('30 no. 203x203x46 UC, 3.2m long, bolted, roof plant room')
  await page.getByTestId('capture-assist').click()
  await label(page, 'L2')
  await expect(page.getByTestId('capture-family')).toHaveValue('steel_section')
  await expect(page.getByTestId('capture-section')).toHaveValue('UC 203x203x46')
  await expect(page.getByTestId('capture-pieces')).toHaveValue('30')
  await expect(page.getByTestId('capture-length')).toHaveValue('3.2')
  await expect(page.getByTestId('capture-recoverability-A')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('capture-location')).toHaveValue('roof plant room')
  await page.getByTestId('capture-photo').setInputFiles(path.resolve('e2e/fixtures/sample-photo.jpg'))
  await expect(page.getByTestId('capture-photos')).toBeVisible()
  await page.getByTestId('capture-condition-A').click()
  await expect(page.getByTestId('capture-expected-month')).toHaveValue('1')
  await expect(page.getByTestId('capture-expected-year')).toHaveValue('2027')
  await label(page, 'L43')
  await expectNoHorizontalScroll(page)
  await expectTouchTargets(page)
  await page.getByTestId('capture-save').click()
  await expect(page.getByTestId('saved-tag')).toHaveText('TH-12')
  await expect(page.getByTestId('saved-mass')).toHaveText('4.43 t')
  await expect(page.getByTestId('saved-carbon')).toHaveText('7.5 tCO2e')
  await expect(page.getByTestId('saved-guide')).toHaveText('£670 per tonne')
  await expect(page.getByTestId('saved-photos')).toHaveText('1 photo, Private')
  await expect(page.getByTestId('saved-expected')).toHaveText('January 2027')

  // Step 2. Decide what to recover (Tom)
  await page.setViewportSize({ width: 1440, height: 900 })
  await setPersona(page, P.tom)
  await go(page, `/buildings/${TIVERNE_ID}/priority`)
  assertRoute(page)
  await expect(page.locator('[data-testid^="priority-row-"]')).toHaveCount(12)
  await expect(page.getByTestId('priority-tag-text-1')).toHaveText('TH-02')
  await expect(page.getByTestId('priority-score-1')).toHaveText('68.7')
  await expect(page.getByTestId('priority-tag-text-12')).toHaveText('TH-12')
  await expect(page.getByTestId('priority-score-12')).toHaveText('14.5')
  await expect(page.getByTestId('priority-reason-TH-09')).toContainText('Recycle rather than recover')
  await expect(page.getByTestId('priority-reason-TH-10')).toContainText('Recycle rather than recover')
  await expect(page.getByTestId('priority-recoverable')).toHaveText('£202,966.91')
  await expect(page.getByTestId('priority-top-three')).toHaveText('54.2%')
  await label(page, 'L2')
  await label(page, 'L41')
  await page.getByTestId('priority-calc-1').click()
  const calc = page.getByTestId('priority-calc-1-panel')
  await expect(calc).toContainText('22.7')
  await expect(calc).toContainText('30.0')
  await expect(calc).toContainText('10.0')
  await expect(calc).toContainText('6.0')
  await page.keyboard.press('Escape')

  // Step 3. Publish without leaking (Tom)
  await go(page, `/buildings/${TIVERNE_ID}/listings`)
  assertRoute(page)
  await expect(page.locator('[data-testid^="lot-visibility-"]').filter({ hasText: 'Shared privately with selected projects' })).toHaveCount(5)
  await page.getByTestId('select-lot-TH-01').click()
  await page.getByTestId('publish-visibility').selectOption('open')
  await expect(page.getByTestId('disclosure-score')).toHaveText('10')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Low')
  await label(page, 'L9')
  await page.getByTestId('location-level').selectOption('local_authority')
  await expect(page.getByTestId('disclosure-score')).toHaveText('25')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Medium')
  await expect(page.getByTestId('disclosure-inferences')).toContainText('Local authority shown')
  await label(page, 'L34')
  await page.getByTestId('timing-level').selectOption('month')
  await expect(page.getByTestId('disclosure-score')).toHaveText('35')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Medium')
  await page.getByTestId(`photo-public-${th01.id}-pho_th01-tick`).check()
  await expect(page.getByTestId('disclosure-score')).toHaveText('45')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('High')
  await expect(page.getByTestId('publish')).toBeDisabled()
  await expect(page.getByTestId('publish-blocked')).toHaveText('Publishing is blocked at this disclosure level.')
  await page.getByTestId('reset-defaults').click()
  await expect(page.getByTestId('disclosure-score')).toHaveText('10')
  await expect(page.getByTestId('disclosure-band-text')).toHaveText('Low')
  await expect(page.getByTestId('preview-location')).toHaveText('Central London')
  await expect(page.getByTestId('preview-availability')).toHaveText('Available from Q1 2027')
  await expect(page.getByTestId('publish-ask')).toHaveValue('800')
  await expect(page.getByTestId('publish-reserve')).toHaveValue('730')
  await page.getByTestId('publish').click()
  await expect(page.getByTestId('lot-visibility-TH-01')).toHaveText('Published to the marketplace')
  await expect(page.getByTestId('lot-public-id-TH-01')).toHaveText('L-9F4CQQ')
  await expect(page.getByTestId('selected-ask')).toContainText('£800 per tonne')
  await expect(page.getByTestId('selected-reserve')).toContainText('£730 per tonne')
  await expect(page.getByTestId('holding-line').first()).toHaveText('Holding unsold stock would use up the gain over scrap in about 75.9 months')
  await label(page, 'L28')

  // Step 4. Find it (Priya)
  await setPersona(page, P.priya)
  await go(page, '/market')
  assertRoute(page)
  await expect(page.getByTestId('browse-card-L-9F4CQQ')).toBeVisible()
  await expectNoLotPrivate(page)
  await page.getByTestId('browse-card-L-9F4CQQ').locator('a').click()
  await expect(page).toHaveURL(/#\/market\/L-9F4CQQ$/)
  assertRoute(page)
  await expect(page.locator('main svg[role="img"]').first()).toBeVisible()
  await expect(page.getByTestId('listing-title')).toHaveText('UB 457x191x67, 7.5 m')
  await expect(page.getByTestId('listing-quantity')).toHaveText('48 pieces')
  await expect(page.getByTestId('listing-mass')).toHaveText('24.16 t')
  await expect(page.getByTestId('listing-grade')).toHaveText('To be confirmed by testing')
  await expect(page.getByTestId('listing-test-status')).toHaveText('Untested')
  await expect(page.getByTestId('listing-location')).toHaveText('Central London')
  await expect(page.getByTestId('listing-availability')).toHaveText('Available from Q1 2027')
  await expect(page.getByTestId('listing-price')).toHaveText('£715 to £825 per tonne')
  await expect(page.getByTestId('listing-signal')).toHaveText('Market signal: High demand')
  await expect(page.getByTestId('listing-carbon')).toHaveText('41.0 tCO2e')
  await expect(page.getByTestId('listing-listed')).toHaveText('Surveyed. Listed October 2026.')
  await label(page, 'L10')
  await expectNoLotPrivate(page)
  for (const s of lotPrivateStrings(seed.lots['lot_7fk2qa'], th01, seed.buildings[TIVERNE_ID], seed)) expect(page.url()).not.toContain(encodeURIComponent(s))
  await page.getByTestId('listing-carbon-calc').click()
  await expect(page.getByTestId('listing-carbon-calc-panel')).toContainText(LABELS.L11)
  await expect(page.getByTestId('listing-carbon-calc-panel')).toContainText(LABELS.L12)
  await page.keyboard.press('Escape')
  await page.getByTestId('listing-price-calc').click()
  await expect(page.getByTestId('listing-price-calc-panel')).toContainText(LABELS.L2)
  await page.keyboard.press('Escape')

  // Step 5. Match a schedule (Isla, the client)
  await setPersona(page, P.isla)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  assertRoute(page)
  await page.getByTestId('load-sample-schedule').click()
  await expect(page.getByTestId('match-lines')).toHaveText('6 lines, 102 members')
  await expect(page.getByTestId('match-matched')).toHaveText('60 of 102 members matched (58.8%)')
  await label(page, 'L6')
  await page.getByTestId('open-terms').click()
  await label(page, 'L7')
  await page.getByTestId('accept-terms').click()
  await expect(page.getByTestId('match-matched')).toHaveText('96 of 102 members matched (94.1%)')
  await expect(page.getByTestId('match-open-only')).toHaveText('Open market only: 60 of 102')
  const alloc = async (ref: string, id: string, pieces: string) => expect(page.getByTestId(`alloc-pieces-${ref}-${id}`)).toHaveText(pieces)
  await alloc('R1', 'L-9F4CQQ', '48')
  await alloc('R1', 'L-NHZ32R', '4')
  await alloc('R2', 'L-WPX5A6', '12')
  await alloc('R3', 'L-MNY55K', '10')
  await alloc('R4', 'L-6DN4K3', '8')
  await expect(page.getByTestId('reason-R5')).toHaveText('No stock long enough (longest visible in this serial size is 9.5 m)')
  await alloc('R6', 'L-FQK92P', '14')
  await expect(page.getByTestId('alloc-storage-R1-L-9F4CQQ')).toHaveText('Storage 13 to 16 months')
  await expect(page.getByTestId('alloc-grade-R1-L-9F4CQQ')).toHaveText('Grade to be confirmed by testing')
  await label(page, 'L2')
  await label(page, 'L4')
  await expectNoLotPrivate(page)
  await page.getByTestId('add-to-plan-R1-L-9F4CQQ').click()
  await expect(page.getByText('The reuse plan has 1 item.')).toBeVisible()

  // Step 6. Bridge the gap (Isla)
  await go(page, `/projects/${MERROWGATE_ID}/plan`)
  assertRoute(page)
  await expect(page.getByTestId('package-route')).toHaveText('Via storage hub')
  await expect(page.getByTestId('package-facility')).toHaveText('Open yard, Tilbury')
  await expect(page.getByTestId('facility-HUB-TILB')).toContainText('Lowest estimated total')
  await expect(page.getByTestId('package-testing')).toBeChecked()
  await expect(page.getByTestId('package-storage')).toHaveText('Storage 13 to 16 months')
  await label(page, 'L5')
  await expect(page.getByTestId('package-line-material')).toHaveText('£18,600.12')
  await expect(page.getByTestId('package-line-testing')).toHaveText('£1,800.00')
  await expect(page.getByTestId('package-line-storage')).toHaveText('£1,352.74')
  await expect(page.getByTestId('package-line-handlingOut')).toHaveText('£217.40')
  await expect(page.getByTestId('package-line-delivery')).toHaveText('£235.80')
  await expect(page.getByTestId('package-total')).toHaveText('£22,206.06')
  await expect(page.getByTestId('package-new')).toHaveText('£23,189.76')
  await expect(page.getByTestId('package-saving')).toHaveText('Saving £983.70 (4.2%)')
  await expect(page.getByTestId('package-break-even')).toHaveText('Break-even storage 27.6 months')
  await expect(page.getByTestId('package-carbon')).toHaveText('Avoided carbon 39.3 tCO2e')
  await expect(page.getByTestId('facility-total-HUB-TILB')).toHaveText('£22,206.06')
  await expect(page.getByTestId('facility-total-HUB-BARK')).toHaveText('£22,779.36')
  await expect(page.getByTestId('facility-total-HUB-PARK')).toHaveText('£26,324.13')
  await expectNoLotPrivate(page)

  // Step 7. Negotiate through an agent (Isla)
  await expect(page.getByTestId('mandate-open')).toHaveValue('700')
  await expect(page.getByTestId('mandate-max')).toHaveValue('780')
  await page.getByTestId('start-negotiation').click()
  await label(page, 'L3')
  const entries = page.locator('[data-testid^="negotiation-entry-"]')
  await expect(entries).toHaveCount(7)
  const texts = await entries.allTextContents()
  expect(texts.map((t) => t.replace(/^(Seller agent|Buyer agent|Outcome)/, '').trim())).toEqual(['Ask £800', 'Bid £700', 'Ask £760', 'Bid £725', 'Ask £745', 'Bid £735', 'Agreed in principle at £740 per tonne'])
  await expect(page.getByTestId('buyer-approve')).toHaveText(LABELS.L21)
  await page.getByTestId('buyer-approve').click()
  await expect(page.getByTestId('package-total')).toHaveText('£21,481.38')
  await expect(page.getByTestId('package-saving')).toHaveText('Saving £1,708.38 (7.4%)')
  await expect(page.getByTestId('plan-status-text-L-9F4CQQ')).toHaveText('Awaiting seller approval')
  expect(await mainText(page)).not.toContain('730')
  await expectNoLotPrivate(page)

  // Step 8. Seller approves (Tom, then Isla)
  await setPersona(page, P.tom)
  await go(page, '/offers')
  assertRoute(page)
  await expect(page.getByTestId('offer-buyer')).toHaveText('Design team, commercial project, Inner London East, needed by Q2 2028')
  await expect(page.getByTestId('offer-price')).toHaveText('£740 per tonne for 48 pieces (24.16 t)')
  await expect(page.getByTestId('offer-hub')).toHaveText('Deliver to: Open yard, Tilbury')
  await expect(page.getByTestId('offer-net')).toHaveText('Net proceeds £15,979.60')
  await expect(page.getByTestId('offer-gain')).toHaveText('Gain over scrap £8,491.24')
  {
    const text = await mainText(page)
    for (const s of PROJECT_PRIVATE) expect(text, `seller-side content leaks "${s}"`).not.toContain(s)
  }
  await page.getByTestId('seller-approve').click()
  await label(page, 'L22')
  await expect(page.getByTestId('seller-deal-status')).toHaveText('Confirmed')
  await expect(page.getByTestId('seller-deal-buyer')).toHaveText('Lantern Quay Developments')
  await expect(page.getByTestId('seller-deal-contact')).toHaveText('Isla Brennan, Lantern Quay Developments')
  await expect(page.getByTestId('seller-deal-handover')).toHaveText('Handover 15 March 2027 at Open yard, Tilbury')
  await expect(page.getByTestId('seller-deal-inbound')).toHaveText('Inbound haulage £248.40, booked')
  {
    const text = await mainText(page)
    for (const s of dateFormats('2028-04-03')) expect(text).not.toContain(s)
    expect(text).not.toMatch(/\b13 months\b/)
    expect(text).not.toContain('21,227.74')
  }
  await setPersona(page, P.isla)
  await go(page, `/projects/${MERROWGATE_ID}/deals`)
  assertRoute(page)
  await expect(page.getByTestId('buyer-deal-status')).toHaveText('Confirmed')
  await expect(page.getByTestId('buyer-deal-seller')).toHaveText('Ostlea Estates')
  await expect(page.getByTestId('buyer-deal-contact')).toHaveText('Tom Ashby')
  await expect(page.getByTestId('buyer-deal-handover')).toHaveText('Handover 15 March 2027')
  await expect(page.getByTestId('buyer-deal-storage')).toHaveText('Storage 13 months')
  await expect(page.getByTestId('buyer-deal-total')).toHaveText('Total £21,227.74')
  await expect(page.getByTestId('buyer-deal-saving')).toHaveText('Saving £1,962.02 (8.5%)')
  await expect(page.getByTestId('buyer-deal-break-even')).toHaveText('Break-even storage 36.2 months')
  await label(page, 'L23')
  await label(page, 'L22')
  await expectNoLotPrivate(page, true)
  await go(page, '/market/L-9F4CQQ')
  await expect(page.getByTestId('listing-title')).toBeVisible()
  await expect(page.locator('main')).toContainText('No longer available')
  await go(page, '/market')
  await expect(page.getByTestId('browse-card-L-9F4CQQ')).toHaveCount(0)

  // Step 9. Logistics (Isla)
  await go(page, `/projects/${MERROWGATE_ID}/deals`)
  await page.getByTestId('arrange-delivery').click()
  await label(page, 'L3')
  await expect(page.getByTestId('quote-Haulier-A')).toContainText("Haulier A£235.803 days' notice")
  await expect(page.getByTestId('quote-Haulier-C')).toContainText("Haulier C£260.105 days' notice")
  await expect(page.getByTestId('quote-Haulier-B')).toContainText("Haulier B£264.252 days' notice")
  await expect(page.getByTestId('quote-Haulier-A')).toContainText('Cheapest that meets the dates')
  await page.getByTestId('approve-booking').click()
  await expect(page.getByTestId('delivery-booked')).toContainText('Delivery booked for 3 April 2028')
  await expect(page.getByTestId('custody-agreed')).toContainText('Agreed 7 October 2026')
  await expect(page.getByTestId('custody-agreed')).toContainText('done')
  await expect(page.getByTestId('custody-handover')).toContainText('Handover at hub 15 March 2027')
  await expect(page.getByTestId('custody-tested')).toContainText('Tested 29 March 2027')
  await expect(page.getByTestId('custody-delivered')).toContainText('Delivered 3 April 2028')
  await expect(page.getByTestId('custody-delivered')).toContainText('planned')
  expect(await mainText(page)).not.toContain('248.40')
  await expectNoLotPrivate(page, true)

  // Step 10. Prove it (Marcus)
  await setPersona(page, P.marcus)
  await go(page, `/projects/${MERROWGATE_ID}/compliance`)
  assertRoute(page)
  await expect(page.getByTestId('content-secured')).toHaveText('Reused and recycled content by value: 20.06% secured')
  await expect(page.getByTestId('content-aim')).toHaveText('Aim: at least 20%')
  await expect(page.getByTestId('content-with-plan')).toHaveText('With plan 20.06%')
  await expect(page.getByTestId('content-without-reuse')).toHaveText('Without reuse 17.62%')
  await expect(page.getByTestId('contribution-bom08')).toHaveText('+2.00')
  await expect(page.getByTestId('contribution-bom10')).toHaveText('+0.29')
  await expect(page.getByTestId('contribution-bom03')).toHaveText('+0.15')
  await expect(page.getByTestId('avoided-carbon')).toHaveText('Upfront carbon avoided against buying new (A1-A4): 87.1 tCO2e')
  await expect(page.getByTestId('reclaimed-mass')).toHaveText('Reclaimed material secured: 126.96 t')
  await label(page, 'L17')
  await label(page, 'L16')
  await label(page, 'L15')
  await label(page, 'L11')
  await label(page, 'L19')
  await expectNoLotPrivate(page, true)
  {
    const text = await mainText(page)
    expect(text).not.toContain('Durnley House')
    expect(text).not.toContain('Pellory Estates')
  }
  const dl1 = page.waitForEvent('download')
  await page.getByTestId('export-compliance').click()
  const d1 = await dl1
  expect(d1.suggestedFilename()).toBe('merrowgate-wharf-compliance-2026-10-07.xlsx')
  const f1 = path.join(testInfo.outputDir, d1.suggestedFilename())
  await d1.saveAs(f1)
  {
    const { text, sheets } = await workbookText(f1)
    expect(sheets).toContain('Summary')
    expect(text).toContain(LABELS.L20)
    for (const s of LOT_PRIVATE) if (!EXCHANGED.includes(s)) expect(text, `workbook leaks "${s}"`).not.toContain(s)
  }
  // Print layout: A4, no clipped table, and a PDF.
  await page.emulateMedia({ media: 'print' })
  await page.setViewportSize({ width: 794, height: 1123 })
  const clipped = await page.evaluate(() => [...document.querySelectorAll('main table')].filter((t) => t.scrollWidth > (t.parentElement?.clientWidth ?? 0) + 1).length)
  expect(clipped, 'tables clipped in print').toBe(0)
  await expect(page.getByTestId('label-L20').first()).toBeVisible()
  const pdf = await page.pdf({ format: 'A4', printBackground: true })
  expect(pdf.byteLength).toBeGreaterThan(1000)
  await page.emulateMedia({ media: 'screen' })
  await page.setViewportSize({ width: 1440, height: 900 })

  // Step 11. Ingest a demolition bill (Marcus)
  await go(page, `/engagements/${DURNLEY_ID}/waste`)
  assertRoute(page)
  await page.getByTestId('load-sample-bill').click()
  await label(page, 'L2')
  await expect(page.getByTestId('rows-read')).toHaveText('20 rows read')
  await expect(page.getByTestId('rows-skipped')).toHaveText('2 title rows and 1 total row skipped')
  await expect(page.getByTestId('confidence-counts')).toHaveText('14 high confidence, 5 medium, 1 needs review')
  await expect(page.getByTestId('stated-total')).toHaveText('Stated total 11,369.2 t matches the rows')
  await expect(page.getByTestId('diversion')).toHaveText('Diversion from landfill 97.5%')
  await expect(page.getByTestId('unresolved-notice')).toHaveText('1 row (6.0 t) is not counted until it is reviewed')
  await page.getByTestId('row-20-stream').selectOption('mixed_cd')
  await page.getByTestId('row-20-destination').selectOption('landfill')
  await expect(page.getByTestId('diversion')).toHaveText('Diversion from landfill 97.4%')
  await expect(page.getByTestId('diversion-aim')).toHaveText('Aim: at least 95%')
  await expect(page.getByTestId('reuse-rate')).toHaveText('Reuse rate 3.1%')
  await expect(page.getByTestId('reused-off-site')).toHaveText('Components reused off site 351.0 t')
  await expect(page.getByTestId('recycled-on-site')).toHaveText('Recycled on site 1,200.0 t')
  await expect(page.getByTestId('carbon-benefit')).toHaveText('Potential carbon benefit of reuse 461.4 tCO2e')
  await expect(page.getByTestId('hazardous')).toHaveText('Hazardous waste 14.2 t, reported separately')
  await expect(page.getByTestId('intensity')).toHaveText('0.72 t per m2 GIA')
  await label(page, 'L18')
  await label(page, 'L13')
  await label(page, 'L16')
  {
    const text = await mainText(page)
    for (const s of PROJECT_PRIVATE) expect(text, `waste screen leaks "${s}"`).not.toContain(s)
  }
  const dl2 = page.waitForEvent('download')
  await page.getByTestId('export-waste').click()
  const d2 = await dl2
  expect(d2.suggestedFilename()).toBe('durnley-house-waste-and-reuse-2026-10-07.xlsx')
  const f2 = path.join(testInfo.outputDir, d2.suggestedFilename())
  await d2.saveAs(f2)
  expect((await workbookText(f2)).sheets).toContain('Arisings')

  // Step 12. Run the platform (operator)
  await setPersona(page, P.operator)
  await go(page, '/operator/ledger')
  assertRoute(page)
  const deal = page.getByTestId('ledger-deal-L-9F4CQQ')
  await expect(deal.getByTestId('ledger-line-commission')).toHaveText('Commission £1,430.04')
  await expect(deal.getByTestId('ledger-line-brokerage')).toHaveText('Storage brokerage £153.39')
  await expect(deal.getByTestId('ledger-line-referral')).toHaveText('Testing referral £180.00')
  await expect(deal.getByTestId('ledger-line-transport')).toHaveText('Transport margin £24.21')
  await expect(deal.getByTestId('ledger-deal-total')).toHaveText('Deal total £1,787.64')
  await expect(page.getByTestId('ledger-to-date')).toHaveText('Transactions and data to date £16,192.44')
  await expect(page.getByTestId('ledger-subscriptions')).toHaveText('Subscriptions, annual £70,800.00')
  await label(page, 'L31')
  {
    const text = await mainText(page)
    for (const s of ['Tiverne House', 'Garnet Row', 'Corvane Insurance', 'Meridale Partners']) expect(text).not.toContain(s)
  }
  await go(page, '/operator/models')
  await expect(page.getByTestId('model-agency')).toHaveText('Agency £1,787.64, no capital employed')
  await expect(page.getByTestId('model-principal')).toHaveText('Principal: margin £3,785.28 on capital of £16,868.10 (22.4%)')
  await expect(page.getByTestId('model-candidate')).toHaveText('Candidate to buy')
  await expect(page.getByTestId('model-forward')).toHaveText('Forward sale £1,966.39')
  await label(page, 'L29')
  await label(page, 'L30')
  await label(page, 'L2')
})

/** Every route the architect can open in the seed, for P3, P7 and P11. */
const ARCHITECT_ROUTES = ['/market', '/market/shared', '/saved', '/projects/new', '/market/L-NHZ32R', ...[MERROWGATE_ID, SALLOW_ID, FERRYMOOR_ID].flatMap((id) => [`/projects/${id}`, `/projects/${id}/wishlist`, `/projects/${id}/spec`, `/projects/${id}/match`])]

test('labels off the path, the stubs, and P3, P4, P5b and P7 on the version 1.0 routes', async ({ page, entry }) => {
  test.setTimeout(180_000)
  await fresh(page, entry)

  // The selling owner before any deal: L41, L43, L28 and P4 on the blind sharing list and on offers.
  await setPersona(page, P.tom)
  await go(page, `/buildings/${TIVERNE_ID}/priority`)
  assertRoute(page)
  await label(page, 'L41')
  await expectNoProjectPrivate(page)
  await go(page, `/buildings/${TIVERNE_ID}/inventory`)
  assertRoute(page)
  await label(page, 'L43')
  await expectNoProjectPrivate(page)
  await go(page, `/buildings/${TIVERNE_ID}/listings`)
  assertRoute(page)
  await expect(page.getByTestId(`share-row-${MERROWGATE_ID}`)).toBeVisible()
  await expect(page.getByTestId(`share-text-${MERROWGATE_ID}`)).toContainText('Design team')
  await expect(page.locator('[data-testid^="share-row-"]')).toHaveCount(3)
  await expectNoProjectPrivate(page)
  await go(page, '/offers')
  assertRoute(page)
  await expectNoProjectPrivate(page)

  // The surveyor: L43 and the photo stub on capture.
  await setPersona(page, P.dana)
  await go(page, `/buildings/${TIVERNE_ID}/capture`)
  assertRoute(page)
  await label(page, 'L43')
  await label(page, 'L8')
  await page.getByTestId('stub-photo').click()
  await expect(page.getByTestId('stub-photo-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')

  // The architect. P5b: a shared lot before the terms, then after accepting the terms of a project the owner has not approved.
  await setPersona(page, P.priya)
  await go(page, '/market/L-WPX5A6')
  await expect(page.getByTestId('listing-not-available')).toHaveText(LABELS.L26)
  await go(page, '/market/shared')
  await label(page, 'L6')
  await expect(page.getByTestId(`shared-not-yet-${SALLOW_ID}`)).toBeVisible()
  await expect(page.getByTestId(`shared-claim-${SALLOW_ID}`)).toHaveCount(0)
  await page.getByTestId(`open-terms-${SALLOW_ID}`).click()
  await label(page, 'L7')
  await page.getByTestId('accept-terms').click()
  await expect(page.getByTestId(`shared-none-${SALLOW_ID}`)).toBeVisible()
  await go(page, '/market/L-WPX5A6')
  await expect(page.getByTestId('listing-not-available')).toHaveText(LABELS.L26)
  // L14 on unused surplus. The architect never sees reserve copy (13.10).
  await go(page, '/market/L-YZ2C7H')
  await expect(page.getByTestId('listing-carbon')).toHaveText(LABELS.L14)
  await go(page, '/market/L-Q23X7N')
  await expect(page.getByTestId('listing-title')).toBeVisible()
  await expect(page.getByTestId('label-L25')).toHaveCount(0)
  await expect(page.getByTestId('reserve-steel')).toHaveCount(0)
  // L35 on the BIM family control, L36 under a swatch, L37 by the band, L42 on the geometry control, L38 on the timeline.
  await label(page, 'L35')
  await expect(page.getByTestId('label-L36')).toHaveText(LABELS.L36)
  await label(page, 'L37')
  await label(page, 'L42')
  await expect(page.getByTestId('label-L38')).toHaveCount(0)
  await page.getByTestId('listing-project-picker').selectOption(MERROWGATE_ID)
  await label(page, 'L38')
  await expect(page.getByTestId('listing-fit')).toBeVisible()
  // Timber joists have no recorded section: the geometry control says so.
  await go(page, '/market/L-CJGQP7')
  await expect(page.getByTestId('download-dxf')).toBeDisabled()
  await expect(page.getByTestId('download-obj')).toBeDisabled()
  await expect(page.getByTestId('geometry-reason')).toHaveText('No recorded section size')
  // L35 on the greyed match schedule, with the V2 tag in the rail.
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await expect(page.getByTestId('match-v2')).toBeVisible()
  await label(page, 'L35')
  await expect(page.getByTestId(`nav-${MERROWGATE_ID}-match-v2`)).toHaveText('V2')
  // L40, L37, L38, L42 on a wish list, L39 and L20 on the spec sheet (Sallow Court holds two pending items).
  await go(page, `/projects/${SALLOW_ID}/wishlist`)
  await expect(page.locator('[data-testid^="wish-row-"]')).toHaveCount(2)
  await label(page, 'L40')
  await label(page, 'L37')
  await label(page, 'L38')
  await label(page, 'L42')
  await go(page, `/projects/${SALLOW_ID}/spec`)
  await page.getByTestId('spec-toggle-draft').click()
  await expect(page.locator('[data-testid^="spec-block-"]')).toHaveCount(2)
  await label(page, 'L39')
  await label(page, 'L20')
  // P3, P7 and P11 on every architect route.
  for (const route of ARCHITECT_ROUTES) {
    await go(page, route)
    await expect(page.locator('main h1').first()).toBeVisible()
    assertRoute(page)
    await expectNoLotPrivate(page)
    await expectArchitectOnly(page)
  }

  // The client: L25 on a listing of another family, the BIM stub, L6 and L7 on her matcher, L27 and L24 after the terms.
  await setPersona(page, P.isla)
  await go(page, '/market/L-Q23X7N')
  await label(page, 'L25')
  await go(page, `/projects/${MERROWGATE_ID}/approvals`)
  assertRoute(page)
  await expectNoLotPrivate(page)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await page.getByTestId('load-sample-schedule').click()
  await label(page, 'L6')
  await page.getByTestId('open-terms').click()
  await label(page, 'L7')
  await page.getByTestId('accept-terms').click()
  await page.getByTestId('alloc-link-R2-L-WPX5A6').click()
  await expect(page.locator('main')).toContainText(LABELS.L27)
  await expectNoLotPrivate(page)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await expectNoLotPrivate(page)
  await page.getByTestId('add-to-plan-R1-L-NHZ32R').click()
  await go(page, `/projects/${MERROWGATE_ID}/plan`)
  assertRoute(page)
  await label(page, 'L24')
  await expectNoLotPrivate(page)
  await go(page, `/projects/${MERROWGATE_ID}/deals`)
  assertRoute(page)
  await expectNoLotPrivate(page)
  await go(page, `/projects/${MERROWGATE_ID}/match`)
  await page.getByTestId('stub-bim').click()
  await expect(page.getByTestId('stub-bim-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')

  // The consultant: the wish list review and compliance carry no lot private string; the PDF stub on the waste screen.
  await setPersona(page, P.marcus)
  for (const route of [`/projects/${MERROWGATE_ID}/compliance`, `/projects/${MERROWGATE_ID}/review`]) {
    await go(page, route)
    assertRoute(page)
    await expectNoLotPrivate(page)
  }
  await go(page, `/engagements/${DURNLEY_ID}/waste`)
  assertRoute(page)
  await page.getByTestId('stub-pdf').click()
  await expect(page.getByTestId('stub-pdf-label')).toHaveText(LABELS.L33)
  await page.keyboard.press('Escape')

  // L32 and the version 1.0 parameters on Assumptions, the About screen's fictional line, the empty model comparison.
  await go(page, '/assumptions')
  await label(page, 'L32')
  await go(page, '/about')
  await expect(page.getByTestId('about-fictional')).toHaveText('Every company, person, building and address in this prototype is fictional.')
  await setPersona(page, P.operator)
  await go(page, '/operator/models')
  await expect(page.locator('main')).toContainText('Confirm a deal to compare models.')
})

test("layout at 1024 and 1440, phone width for capture, browse, listing and wish list, and reset removes only this app's storage", async ({ page, entry }) => {
  test.setTimeout(300_000)
  await open(page, entry)
  await page.evaluate(() => localStorage.setItem('other-app', 'kept'))
  await setUpTo(page, 12)
  const screens: [string, string][] = [
    [P.dana, `/buildings/${TIVERNE_ID}/capture`], [P.dana, `/buildings/${TIVERNE_ID}/inventory`], [P.dana, `/buildings/${HARROWDEN_ID}/inventory`],
    [P.tom, `/buildings/${TIVERNE_ID}/inventory`], [P.tom, `/buildings/${TIVERNE_ID}/inventory/itm_7fk2qa`], [P.tom, `/buildings/${TIVERNE_ID}/priority`], [P.tom, `/buildings/${TIVERNE_ID}/listings`], [P.tom, '/offers'],
    ...ARCHITECT_ROUTES.map((r): [string, string] => [P.priya, r]), [P.priya, '/market/L-9F4CQQ'],
    [P.isla, `/projects/${MERROWGATE_ID}/approvals`], [P.isla, `/projects/${MERROWGATE_ID}/match`], [P.isla, `/projects/${MERROWGATE_ID}/plan`], [P.isla, `/projects/${MERROWGATE_ID}/deals`],
    [P.marcus, `/projects/${MERROWGATE_ID}/compliance`], [P.marcus, `/projects/${MERROWGATE_ID}/review`], [P.marcus, `/engagements/${DURNLEY_ID}/waste`],
    [P.operator, '/operator/ledger'], [P.operator, '/operator/models'], [P.operator, '/assumptions'], [P.operator, '/about'],
  ]
  for (const width of [1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await go(page, '/')
    await expectNoHorizontalScroll(page)
    for (const [persona, route] of screens) {
      await setPersona(page, persona)
      await go(page, route)
      await expect(page.locator('main h1').first()).toBeVisible()
      await expectNoHorizontalScroll(page)
    }
  }

  // Phone width (13.11): capture, browse with the filter sheet, a listing, and a wish list with rows, at 44 px targets.
  await page.setViewportSize({ width: 390, height: 844 })
  const phone = async () => {
    await expect(page.locator('main h1').first()).toBeVisible()
    await expectNoHorizontalScroll(page)
    await expectTouchTargets(page)
  }
  await setPersona(page, P.dana)
  await go(page, `/buildings/${TIVERNE_ID}/capture`)
  await phone()
  await setPersona(page, P.priya)
  await go(page, '/market')
  await phone()
  await page.getByTestId('open-more-filters').click()
  await expect(page.getByTestId('more-filters')).toHaveAttribute('data-side', 'bottom')
  await expectTouchTargets(page)
  await page.getByTestId('more-filters-done').click()
  await expect(page.getByTestId('more-filters')).toBeHidden()
  await page.getByTestId('open-rail').click()
  await expect(page.getByTestId('rail-sheet')).toBeVisible()
  await expectTouchTargets(page)
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('rail-sheet')).toBeHidden()
  await go(page, '/market/L-NHZ32R')
  await phone()
  await go(page, `/projects/${SALLOW_ID}/wishlist`)
  await expect(page.locator('[data-testid^="wish-row-"]')).toHaveCount(2)
  await phone()

  await page.setViewportSize({ width: 1440, height: 900 })
  await go(page, '/')
  await resetDemo(page)
  const keys = await page.evaluate(() => Object.keys(localStorage))
  expect(keys).toContain('other-app')
  expect(keys.filter((k) => k.startsWith('tallyard-v05') && k !== 'tallyard-v05-state')).toEqual([])
  const dbs = await page.evaluate(async () => (await indexedDB.databases()).map((d) => d.name))
  expect(dbs).not.toContain('tallyard-v05-photos')
  await setPersona(page, P.tom)
  await go(page, `/buildings/${TIVERNE_ID}/inventory`)
  await expect(page.getByTestId('inventory-row-TH-12')).toHaveCount(0)
  await expect(page.getByTestId('inventory-row-TH-11')).toBeVisible()
})
