// Builds the two sample files (06-DATA.md section C) as real files for tests
// and as strings in src/domain/reference/samples.ts for the app.
import ExcelJS from 'exceljs'
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'

const rows = [
  [1, 'Concrete crushed for 6F2', '17 01 01', '6,650', 't', 'Recycled off site', 'Aggregate recycler, Essex'],
  [2, 'Concrete crushed for piling mat', '170101', 1200, 'tonnes', 'Crushed, used on site as piling mat', 'Retained on site'],
  [3, 'Brick and block rubble', '17 01 07', 620, 't', 'Recycling', 'Aggregate recycler, Essex'],
  [4, 'Facing bricks, cleaned (16,000 nr)', '', 36.8, 't', 'Reuse off-site', 'Reclamation yard, Kent'],
  [5, 'Structural steel sections sold for reuse', '', 212400, 'kg', 'Reuse offsite', 'Steel stockholder, East London'],
  [6, 'Steel scrap, mixed sections and rebar', '17 04 05', '1,490', 't', 'Recycled', 'Metal recycler, Thames Estuary'],
  [7, 'Aluminium', '17 04 02', 38, 't', 'recycle', 'Metal recycler, Thames Estuary'],
  [8, 'Curtain walling panels (64 nr)', '', 19.0, 't', 'Re-use (sold)', 'Facade contractor, Midlands'],
  [9, 'Glass', '17 02 02', 64, 't', 'Recycled', 'Glass recycler, Yorkshire'],
  [10, 'Portland stone cladding', '', 54, 't', 'Reuse off site', 'Stone merchant, Dorset'],
  [11, 'Precast cladding panels', '17 01 01', 410, 't', 'Crushed, recycled', 'Aggregate recycler, Essex'],
  [12, 'Timber', '17 02 01', 75, 't', 'Energy recovery (biomass)', 'Biomass plant, Kent'],
  [13, 'Plasterboard', '17 08 02', 96, 't', 'Recycle', 'Gypsum recycler, Midlands'],
  [14, 'RAF panels 600x600 (2,400 nr)', '', 28.8, 't', 'Reuse (sold)', 'Flooring reseller, London'],
  [15, 'Carpet and ceiling tiles', '17 09 04', 48, 't', 'EfW', 'Energy from waste plant, South London'],
  [16, 'Cables and copper', '17 04 11', 21, 't', 'Recycled', 'Metal recycler, Thames Estuary'],
  [17, 'Mixed C&D waste', '17 09 04', 262, 't', 'Landfill', 'Landfill, Essex'],
  [18, 'Mineral wool insulation', '17 06 04', 24, 'te', 'landfill', 'Landfill, Essex'],
  [19, 'ACM, asbestos cement sheet', '17 06 05*', 14.2, 't', 'Hazardous landfill', 'Hazardous waste landfill, Northamptonshire'],
  [20, 'Sundry strip-out items', '', 6, 't', 'TBC', ''],
]

async function buildBill() {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'Sample'
  wb.created = new Date(Date.UTC(2026, 6, 14))
  wb.modified = new Date(Date.UTC(2026, 6, 14))
  const ws = wb.addWorksheet('Arisings')
  ws.addRow(['Durnley House, waste and arisings summary'])
  ws.mergeCells('A1:G1')
  ws.addRow(['Issued by the deconstruction contractor, 14/07/2026'])
  ws.addRow([])
  ws.addRow(['Ref', 'Waste description', 'EWC code', 'Qty', 'UoM', 'Disposal route', 'Destination facility'])
  for (const r of rows) ws.addRow(r.map((c) => (c === '' ? null : c)))
  ws.addRow([])
  ws.addRow(['TOTAL', null, null, '11,369.2', 't', null, null])
  const buffer = await wb.xlsx.writeBuffer()
  return Buffer.from(buffer)
}

const schedule = 'Mark,Section,Length (mm),Qty,Grade\nR1,UB 457x191x67,7200,52,S355\nR2,UB 533x210x92,8400,12,S355\nR3,UC 305x305x118,3600,10,S355\nR4,UB 457x191x74,7200,8,S355\nR5,UB 610x229x125,10500,6,S355\nR6,UB 406x178x54,5500,14,S275\n'

const force = process.argv.includes('--force')
if (!force && existsSync('src/domain/reference/samples.ts') && existsSync('e2e/fixtures/durnley-house-bill.xlsx') && existsSync('e2e/fixtures/merrowgate-wharf-schedule.csv')) {
  console.log('samples already built (pass --force to rebuild)')
  process.exit(0)
}
const bill = await buildBill()
mkdirSync('e2e/fixtures', { recursive: true })
mkdirSync('src/domain/reference', { recursive: true })
writeFileSync('e2e/fixtures/durnley-house-bill.xlsx', bill)
writeFileSync('e2e/fixtures/merrowgate-wharf-schedule.csv', schedule)
const ts = `// Generated by scripts/make-samples.mjs. Do not edit by hand.
// The sample demolition bill (06-DATA.md section C1) as a base64 workbook and
// the sample steel schedule (section C2) as a CSV string.
export const SAMPLE_BILL_XLSX_BASE64 = '${bill.toString('base64')}'
export const SAMPLE_SCHEDULE_CSV = ${JSON.stringify(schedule)}
`
writeFileSync('src/domain/reference/samples.ts', ts)
console.log('wrote samples:', bill.length, 'bytes workbook')
